TDL-25903 API Version Upgrade to V9
singer-io/tap-toggl pull request #19
Opened 2024-05-31 07:51 UTC by Vi6hal

# Description of change
- Includes v8 to v9 migration (#18)
- Additional Changes to users schema 
# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

co-author: @garrettApproachableGeeK on #18

2024-06-03 14:36 UTC, sgandhi1311 commented
@Vi6hal Can you please fix the circleci test?

2024-06-03 15:27 UTC, sgandhi1311 commented on setup.py
>            'requests==2.20.0',
please update the package version to the latest.

2024-06-05 16:28 UTC, mxia commented
Any chance to get the v9 support in soon? Thanks!

2024-06-17 20:10 UTC, mxia commented
Friendly check on getting this released. Thanks!

2024-06-25 16:15 UTC, nolan-redox commented
Hello @sgandhi1311, any chance this can be merged? This would get us back up and running with Stitch Toggl. Much appreciated!

2024-08-12 21:13 UTC, mxia commented
Any update?

2024-11-18 22:34 UTC, nolan-redox commented
@sgandhi1311 is there anything that would help this PR to be merged? The upgrade to v9 would be very helpful to us!

2025-05-20 09:07 UTC, RushiT0122 requested changes

2025-05-20 09:07 UTC, RushiT0122 commented on tap_toggl/toggl.py
> +    return self._get('https://api.track.toggl.com/api/v9/me')
Define the `base_url = "https://api.track.toggl.com/api"` and `version= "v9"` and use those to construct endpoint URL rather than hard coding it for every endpoint.

2025-05-20 09:10 UTC, RushiT0122 commented
@mxia @nolan-redox Just to keep you informed, we’ve prioritized to merge and deploy these changes to production. Please stay tuned for updates.

2025-05-22 06:38 UTC, RushiT0122 approved these changes

2025-05-22 07:02 UTC, rdeshmukh15 commented on setup.py
> +    },
Be consistent with quotes. We generally use double quotes.

2025-05-22 07:04 UTC, rdeshmukh15 commented on tests/test_canary.py
> +        self.assertSetEqual(streams_to_test, synced_stream_names)
Can you please add empty line at the EOF

2025-07-16 17:43 UTC, luandy64 approved these changes

2025-12-05 12:54 UTC, merged